import { Games } from "@/types/games";

export type ZTriviary = {
  alreadyGuessed: boolean;
  dummyOnLoad: boolean;
  goodTimeline: Games;
  guesses: Games[];
  lives: number;
  livesLeft: number;
  played: boolean;
  streak: number;
  bestStreak: number;
  submitButtonText: string;
  timeline: Games;
  timelineOnLoad: Games;
  won: boolean;
  getLivesLeft: () => number;
  getBestStreak: () => number;
  getPlayed: () => boolean;
  getStreak: () => number;
  getTimeline: () => unknown[];
  markAsPlayed: () => void;
  markAsWon: () => void;
  resetPlay: () => void;
  setLastGuess: () => void;
  setBestStreak: () => void;
  setStreak: (arg0: boolean) => void;
  submitAnswer: () => void;
  updateGuesses: (arg0: Games) => void;
  updateLivesLeft: () => void;
  updateTimeline: (arg0: Games) => void;
};
