services:
  app:
    container_name: gaeldle
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - node-modules:/app/node_modules
      - dot-next:/app/.next
      - vscode:/app/.vscode
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: .
          target: /app
          action: sync
    depends_on:
      - database

  database:
    container_name: gaeldle-db
    image: postgres:16
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql

volumes:
  node-modules:
  dot-next:
  vscode:
  pg-data:
