/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/hexclave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["HexclaveAuthController_signInWithPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync game by IGDB ID */
        post: operations["GamesRouter_sync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete game by ID */
        delete: operations["GamesRouter_delete"];
        options?: never;
        head?: never;
        /** Update game details */
        patch: operations["GamesRouter_update"];
        trace?: never;
    };
    "/api/games/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete multiple games by ID */
        delete: operations["GamesRouter_deleteBulk"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/add/validate-one": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate IGDB ID before adding */
        post: operations["GamesRouter_validateIgdbIdAdd"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image-gen/generate-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a single AI image for a game */
        post: operations["ImageGenRouter_generateImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image-gen/delete-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete a generated AI image for a game */
        post: operations["ImageGenRouter_deleteGeneratedImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image-gen/generate-images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate AI images for multiple games */
        post: operations["ImageGenRouter_generateImages"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image-gen/generate-images/{imageGenId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get bulk image generation status */
        get: operations["ImageGenRouter_getImageGenStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image-gen/generate-images/{imageGenId}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream image generation progress via SSE */
        get: operations["ImageGenRouter_stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clue/generate-clue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a text clue for a game */
        post: operations["ClueRouter_generateClue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clue/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get clue generation history for a game */
        get: operations["ClueRouter_getClueHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clue/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a previous clue from history */
        post: operations["ClueRouter_restoreClue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discover/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan for discoverable games from IGDB */
        post: operations["DiscoverRouter_scan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discover/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply selected discover candidates */
        post: operations["DiscoverRouter_apply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sample/upload-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload sample image */
        post: operations["SampleRouter_uploadImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sample/send-message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send sample message to queue */
        post: operations["SampleRouter_sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sample/clear-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear sample message queue */
        post: operations["SampleRouter_clearQueue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SyncGameDto: {
            /**
             * @description IGDB ID of the game
             * @example 1234
             */
            igdb_id: number;
        };
        SyncGameDataDto: {
            id: number;
            igdbId: number;
            name: string;
        };
        SyncGameResponseDto: {
            success: boolean;
            message: string;
            /** @enum {string} */
            operation: "created" | "updated";
            data: components["schemas"]["SyncGameDataDto"];
        };
        GameUpdateInputDto: {
            name?: string;
            imageUrl?: string;
            aiImageUrl?: string;
            aiPrompt?: string;
            summary?: string;
            storyline?: string;
            firstReleaseDate?: number;
            artworks?: Record<string, never>;
            keywords?: Record<string, never>;
            franchises?: Record<string, never>;
            gameEngines?: Record<string, never>;
            gameModes?: Record<string, never>;
            genres?: Record<string, never>;
            involvedCompanies?: Record<string, never>;
            platforms?: Record<string, never>;
            playerPerspectives?: Record<string, never>;
            releaseDates?: Record<string, never>;
            themes?: Record<string, never>;
        };
        GameResponseDto: {
            success: boolean;
            data: Record<string, never>;
        };
        DeleteBulkDto: {
            /** @description Array of game IDs to delete */
            ids: number[];
        };
        DeleteBulkGamesDataDto: {
            deletedIds: number[];
        };
        DeleteBulkGamesResponseDto: {
            success: boolean;
            data: components["schemas"]["DeleteBulkGamesDataDto"];
        };
        DeleteGameDataDto: {
            id: number;
        };
        DeleteGameResponseDto: {
            success: boolean;
            data: components["schemas"]["DeleteGameDataDto"];
        };
        ValidateIgdbIdAddDto: {
            /** @description IGDB ID to validate */
            igdbId: number;
        };
        ValidateIgdbIdAddResponseDto: {
            igdbId: number;
            existsOnIgdb: boolean;
            alreadyInDb: boolean;
            gameName?: string | null;
            canAdd: boolean;
        };
        GenerateImageDto: {
            igdbId: number;
            /** @default false */
            includeStoryline: boolean;
            /** @default false */
            includeGenres: boolean;
            /** @default false */
            includeThemes: boolean;
            artStyle?: string;
            provider: string;
        };
        GenerateImageResponseDto: {
            success: boolean;
            messageId?: string;
        };
        DeleteGeneratedImageDto: {
            igdbId: number;
            artStyle: string;
        };
        DeleteGeneratedImageResponseDto: {
            success: boolean;
            data?: Record<string, never>;
        };
        GenerateImagesDto: {
            numGames: number;
            artStyle: string;
            /** @default false */
            includeStoryline: boolean;
            /** @default false */
            includeGenres: boolean;
            /** @default false */
            includeThemes: boolean;
            provider: string;
        };
        GenerateImagesResponseDto: {
            success: boolean;
            imageGenId: string;
            gamesQueued: number;
        };
        ImageGenFailureDto: {
            igdbId: number;
            gameName: string;
            error: string;
        };
        ImageGenStatusResponseDto: {
            success: boolean;
            imageGenId: string;
            status: string;
            total: number;
            processed: number;
            succeeded: number;
            failed: number;
            failures: components["schemas"]["ImageGenFailureDto"][];
            params: Record<string, never>;
            startedAt?: string | null;
            completedAt?: string | null;
            createdAt: string;
        };
        GenerateClueDto: {
            igdbId: number;
            provider: string;
        };
        GenerateClueResponseDto: {
            success: boolean;
            data: Record<string, never>;
        };
        GameClueHistoryDto: {
            id: number;
            gameId: number;
            igdbId: number;
            name: string;
            clue: string;
            prompt: string;
            provider: string;
            model: string;
            occurredAt: string;
        };
        RestoreClueDto: {
            igdbId: number;
            historyId: number;
        };
        DiscoverScanDto: {
            /** @description Number of games to scan */
            count: number;
        };
        DiscoverCandidateDto: {
            igdbId: number;
            name: string;
            firstReleaseDate?: number | null;
            coverUrl?: string | null;
            totalRating?: number | null;
            totalRatingCount?: number | null;
            genres: string[];
            platforms: string[];
            isAlreadyAdded: boolean;
        };
        DiscoverScanResponseDto: {
            scanEventId: number;
            candidates: components["schemas"]["DiscoverCandidateDto"][];
            totalReturned: number;
            alreadyAddedCount: number;
        };
        DiscoverApplyDto: {
            scanEventId: number;
            selectedIgdbIds: number[];
        };
        DiscoverApplyResultDto: {
            igdbId: number;
            name?: string | null;
            /** @enum {string} */
            status: "created" | "updated" | "error";
            error?: string | null;
        };
        DiscoverApplyResponseDto: {
            success: boolean;
            applyEventId: number;
            results: components["schemas"]["DiscoverApplyResultDto"][];
        };
        SampleUploadImageDto: {
            /** @description Base64 image string */
            image: string;
            /** @default jpg */
            extension: string;
        };
        UploadImageResponseDto: {
            success: boolean;
            url: string;
        };
        SampleSendMessageDto: {
            message: string;
        };
        SampleSendMessageResponseDto: {
            success: boolean;
            messageId?: string;
            message: string;
        };
        SampleClearQueueResponseDto: {
            success: boolean;
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HexclaveAuthController_signInWithPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GamesRouter_sync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncGameDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncGameResponseDto"];
                };
            };
        };
    };
    GamesRouter_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteGameResponseDto"];
                };
            };
        };
    };
    GamesRouter_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameUpdateInputDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponseDto"];
                };
            };
        };
    };
    GamesRouter_deleteBulk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteBulkDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteBulkGamesResponseDto"];
                };
            };
        };
    };
    GamesRouter_validateIgdbIdAdd: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateIgdbIdAddDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateIgdbIdAddResponseDto"];
                };
            };
        };
    };
    ImageGenRouter_generateImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateImageDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateImageResponseDto"];
                };
            };
        };
    };
    ImageGenRouter_deleteGeneratedImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteGeneratedImageDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteGeneratedImageResponseDto"];
                };
            };
        };
    };
    ImageGenRouter_generateImages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateImagesDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateImagesResponseDto"];
                };
            };
        };
    };
    ImageGenRouter_getImageGenStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                imageGenId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageGenStatusResponseDto"];
                };
            };
        };
    };
    ImageGenRouter_stream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                imageGenId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClueRouter_generateClue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateClueDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateClueResponseDto"];
                };
            };
        };
    };
    ClueRouter_getClueHistory: {
        parameters: {
            query: {
                igdbId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameClueHistoryDto"][];
                };
            };
        };
    };
    ClueRouter_restoreClue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestoreClueDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateClueResponseDto"];
                };
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example error */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
    };
    DiscoverRouter_scan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoverScanDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverScanResponseDto"];
                };
            };
        };
    };
    DiscoverRouter_apply: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoverApplyDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverApplyResponseDto"];
                };
            };
        };
    };
    SampleRouter_uploadImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SampleUploadImageDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadImageResponseDto"];
                };
            };
        };
    };
    SampleRouter_sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SampleSendMessageDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleSendMessageResponseDto"];
                };
            };
        };
    };
    SampleRouter_clearQueue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleClearQueueResponseDto"];
                };
            };
        };
    };
}
